Import('*')

INC = [ '#/vm/inc', '#/peripherals/simple_kb', '#/peripherals/simple_term' ]

LIBS = [ 'libminiat', 'libsimple_kb', 'libsimple_term' ]

buildProgram("miniat_console", "console.c", CPPPATH=INC, LIBS=LIBS)
buildProgram("miniat_console_connector", "console_connector.c", CPPPATH=INC, LIBS=LIBS)
buildMash('simple_term.asm')
buildMash('simple_term_flash_demo.asm')
