#define T_EOL                              1
#define T_LABEL                            2
#define T_ALPHA                            3
#define T_CMP                              4
#define T_DRAW                             5
#define T_BRA                              6
#define T_BRAE                             7
#define T_BRANE                            8
#define T_HALT                             9
#define T_FAIL                            10
#define T_LEFT                            11
#define T_RIGHT                           12
#define T_BLANK                           13
#define T_CHARACTER                       14
#define T_STRING                          15
#define T_OFF                             16
